# Generated by Django 4.2.16 on 2024-12-03 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_answer_options_profile_nickname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="content",
            new_name="text",
        ),
    ]
