# Generated by Django 4.2.16 on 2024-12-03 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_answer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["-likes_count"]},
        ),
    ]
