# Generated by Django 4.2.16 on 2024-12-21 22:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_answer_options_answer_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="question",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="app_questio_search__e53742_gin"
            ),
        ),
    ]
